[package]
name = "dfdx-np-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfdx = { git = "https://github.com/coreylowman/dfdx", branch = "main", version = "0.11.1" }
